[package]
name = "esp32"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
csv = "1.1.6"
nom = "6.2.1"
serde = { version = "1.0.127", features = ["derive"] }
